mod about_page;
mod action_log_page;
mod adaptive_engine_page;
mod advanced_power_plan_tuning_page;
mod app_shell;
mod app_suspension_page;
mod background_cpu_restriction_page;
mod background_efficiency_page;
mod by_activity_page;
mod by_cpu_load_page;
mod by_foreground_page;
mod by_running_app_page;
mod by_time_page;
mod core_limiter_page;
mod core_steering_page;
mod dynamic_priority_boost_page;
mod experimental_features_page;
mod gpu_priority_page;
mod io_priority_page;
mod language_and_appearance_page;
mod memory_priority_page;
mod memory_trim_page;
mod overview_page;
mod priority_control_shared;
mod process_list_page;
mod process_priority_page;
mod settings_controls;
mod thread_priority_page;
mod timer_resolution_page;
mod win32_priority_separation_page;
mod winderust_behaviour_page;

pub(in crate::ui::app) use action_log_page::*;
pub(in crate::ui::app) use process_list_page::*;
